### ISSUE TITLE
the images come between each other

### ISSUE THREAD

**Issue by gzoppo** [dockleryxk/ng-simple-slideshow#59] opened 2019-02-11 03:46 UTC
I start the component in image 0 and I have four images in the slide when I use the goToSlide (i) method, where i is equal to for example 3, image 2 and image 3 are shown at the same time.

The 2 is shown automatically, and the third enters with the effect of the slide.

**Comment by KRYNE** [comment] 2019-02-12 04:05
In case if this isn't a error, i need to know the correct way to use the slideshow.

Thanks

**Comment by dockleryxk** [comment] 2019-02-12 13:28
This seems related to #38. I'm still working on a fix for this.

**Comment by KRYNE** [comment] 2019-02-13 05:03
Yes, it is the same problem. Excuse me, I read it before publishing but I had not understood that it was the same.

I see that problem comes from quite some time ago. Do not really look at your code 100%, but look at why I'm interested in solving this problem and if I can help you better.

At first glance, in the first three lines of the goToSlide() I see that there is a double assignment to slideIndex: first `this.slideIndex = index - 1`, and then in setSlideIndex(), `this.slideIndex += indexDirection` (in this case indexDirection = 1).
I think your problem is there, and I do not have complete knowledge of your code to give you a solution, but I imagine that these assignments may need a conditional or maybe be done at another time.

If you give me explanations why I make this assignment in two parts instead of doing it once, I could keep thinking about how we can solve it.

**Comment by dockleryxk** [comment] 2019-02-13 15:17
@KRYNE no problem, I am always happy to discuss. 

Basically, classes are assigned to create sliding animations. The logic goes like this -- goToSlide() is called, so go to the slide right before the slide that is desired (`this.slideIndex = index - 1`), then increment to the desired slide so the animation is triggered.

Perhaps there is a better way or I need more checks to make sure things happen correctly.

**Comment by KRYNE** [comment] 2019-02-14 00:44
Exactly, as I understood it and clearly the problem is that.

In my opinion it is wrong to assign the previous slide to the one that you want to see without performing the slide effect.

As a quick solution I think I should go through all the intermediate slides before I get to the desired one.

**Comment by dockleryxk** [comment] 2019-03-28 13:17
@gzoppo I just saw this but that is a good idea, I will try this!

**Comment by dockleryxk** [comment] 2019-03-28 14:16
I'm going to close this though since it is a duplicate of #38

**Closed by dockleryxk** 2019-03-28 14:16 UTC
Labels: bug
