### ISSUE TITLE
init error loading images use dot

### ISSUE THREAD

**Issue by corsaronero** [dockleryxk/ng-simple-slideshow#44] opened 2018-10-09 09:12 UTC
Hi
the slide work good but when i refresh page click in the first after second slide, in order all work fine, but if  i refresh page and click in the third dot the slide go crazy, also in your example

https://ng-simple-slideshow.firebaseapp.com/

How i fix this bug?

Thanks
Regards

**Comment by dockleryxk** [comment] 2018-10-09 15:41
@corsaronero thank you for the report. This bug is a duplicate of #38 which I am currently investigating. I don't have a solution yet though. Please follow that other issue for updates.

**Closed by dockleryxk** 2018-10-09 15:41 UTC
Labels: duplicate
