### ISSUE TITLE
Error import SlideshowModule

### ISSUE THREAD

**Issue by devcastrojunin** [dockleryxk/ng-simple-slideshow#4] opened 2018-01-04 03:34 UTC
Slide not working in my project :-(

Show this error:
![image](https://user-images.githubusercontent.com/29618716/34549321-f2686bde-f0ee-11e7-8214-efbc97305b84.png)

![image](https://user-images.githubusercontent.com/29618716/34549335-12374f70-f0ef-11e7-9629-aa37869641d7.png)

![image](https://user-images.githubusercontent.com/29618716/34549351-31e37a92-f0ef-11e7-8f11-7931a7fbf57b.png)

**Comment by dockleryxk** [comment] 2018-01-04 17:57
What version of angular?

**Comment by devcastrojunin** [comment] 2018-01-04 18:00
Angular4

**Comment by dockleryxk** [comment] 2018-01-05 14:01
Can you provide a link to your source code or a plunkr to reproduce? Or maybe your package.json? From what you have provided, this error could be caused by anything from duplicate/incorrect importing to something as simple as deleting your node_modules and reinstalling.

**Comment by techworkrocks** [comment] 2018-01-09 11:38
Hi!
I got the same problem using Angular5. Beside the console error above posted by devcastrojunin, I get the following warning during compile:

`WARNING in ./node_modules/ng-simple-slideshow/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\xampp\htdocs\workspace\gemgal\node_modules\webpack\lib\dependencies\C
ontextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\xampp\htdocs\workspace\gemgal\node_modules\webpack\lib\Compilat
ion.js:703:24)
    at Compilation.finish (C:\xampp\htdocs\workspace\gemgal\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\xampp\htdocs\workspace\gemgal\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\xampp\htdocs\workspace\gemgal\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\xampp\htdocs\workspace\gemgal\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\xampp\htdocs\workspace\gemgal\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
 @ ./node_modules/ng-simple-slideshow/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ng-simple-slideshow/ng-simple-slideshow.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts`

Also I tried changing the version dependencies in the package.json of ng-simple-slideshow as they seem to require Angular4. Didn't help.

Did anyone try this module with Angular5 with success?

**Comment by dockleryxk** [comment] 2018-01-09 22:47
@techworkrocks I haven't upgraded this package to angular 5 yet. Maybe that would fix both problems. I will try that asap and comment back here when I have done so

**Comment by dockleryxk** [comment] 2018-01-10 05:29
The newest version (1.0.4) uses Angular 5. Let me know if this doesn't resolve your issue. Closing for now as the [demo](https://ng-simple-slideshow.firebaseapp.com/) is using Angular 5 and it's working just fine.

**Closed by dockleryxk** 2018-01-10 05:29 UTC

**Comment by techworkrocks** [comment] 2018-01-10 10:16
Works perfectly!
Thanks for your quick response!

**Comment by ksangular** [comment] 2019-04-24 13:29
Uncaught TypeError: Cannot read property 'loaded' of undefined
    at ng-simple-slideshow.es5.js:445
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:498)
    at ZoneTask.invoke (zone.js:487)
    at timer (zone.js:2281)

**Comment by dockleryxk** [comment] 2019-04-24 18:07
@ksangular  It looks like you are passing in an undefined slide array

**Comment by ksangular** [comment] 2019-04-25 05:22
@dockleryxk  yes, my bad. Its working fine now. Thank you so much.
